[package]
name = "rusty_im"
version = "0.1.0"
authors = ["andi-makes <26302678+andi-makes@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
